FROM node:18.12 as build
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM node:18.12 as production
WORKDIR /app
COPY package.json .
RUN npm install 
COPY --from=build /app/dist ./dist
CMD node dist/apps/producer/src/main
